appname = "chat_room"

[mysql]
host = "127.0.0.1"
name = "chat"
password = "root1234"
port = 3306
table_prefix = ""
user = "root"

[log]
level = "debug"
path = "logs/chat.log"

[static_path]
filepath = "web/static/file/"

[msg_channel_type]
channel_type = "channel"

kafka_hosts = "kafka:9092"
kafka_topic = "rust-chat-message"